// angular-coursera/src/app/about/about.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { Leader } from '../shared/leader';
import { LeaderService } from '../services/leader.service';
import { flyInOut, expand } from '../animations/app.animation';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css'],
  host: {
    '[@flyInOut]': 'true',
    'style': 'display: block'
  },
  animations: [
    flyInOut(),
    expand()
  ]
})
export class AboutComponent implements OnInit {

  leaders: Leader[];
  errMess: string;

  constructor(private leaderSevice: LeaderService,
    @Inject('BaseURL') private BaseURL) { }

  ngOnInit() {
    this.leaderSevice.getLeaders()
      .subscribe(leaders => this.leaders = leaders,
        errmess => this.errMess = <any>errmess);
  }

}

<div class="container" fxLayout="column" fxLayoutGap="10px">

  <div fxFlex>
    <div>
      <h3>About Us</h3>
      <hr>
    </div>
  </div>

  <div fxFlex>
    <div fxLayout="column" fxLayout.gt-sm="row">
      <div fxFlex="70">
        <h2>Our History</h2>
        <p>Started in 2010, Ristorante con Fusion quickly established itself as a culinary icon par excellence in Hong
          Kong. With its unique brand of world fusion cuisine that can be found nowhere else, it enjoys patronage from
          the A-list clientele in Hong Kong. Featuring four of the best three-star Michelin chefs in the world, you
          never know what will arrive on your plate the next time you visit us.</p>
        <p>The restaurant traces its humble beginnings to <em>The Frying Pan</em>, a successful chain started by our
          CEO, Mr. Peter Pan, that featured for the first time the world's best cuisines in a pan.</p>
      </div>
      <div fxFlex="30">
        <mat-card>
          <mat-card-header>
            <mat-card-title>
              <h2>Facts At a Glance</h2>
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <dl>
              <dt>Started</dt>
              <dd>3 Feb. 2013</dd>
              <dt>Major Stake Holder</dt>
              <dd>HK Fine Foods Inc.</dd>
              <dt>Last Year's Turnover</dt>
              <dd>$1,250,375</dd>
              <dt>Employees</dt>
              <dd>40</dd>
            </dl>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>

  <div fxFlex>
    <mat-card>
      <blockquote>
        <h3>You better cut the pizza in four pieces because
          I'm not hungry enough to eat six.</h3>
        <footer>-- Yogi Berra,
          <cite>The Wit and Wisdom of Yogi Berra,
            P. Pepe, Diversion Books, 2014</cite>
        </footer>
      </blockquote>
    </mat-card>
  </div>


  <div fxFlex *ngIf="leaders">
    <h2>Corporate Leadership</h2>
    <div class="container" fxLayout="column" fxLayoutGap="10px">

      <mat-list fxFlex [@expand]>
        <mat-list-item *ngFor="let leader of leaders">
          <img matListAvatar src="{{BaseURL + leader.image}}" alt={{leader.name}}>
          <p matLine> {{leader.name}} {{leader.abbr}}</p>
          <p matLine> {{leader.designation}}</p>
          <p matLine> {{leader.description}}</p>
        </mat-list-item>
      </mat-list>

    </div>
  </div>

  <div [hidden]="leaders">
    <mat-spinner></mat-spinner><h4>Loading . . . Please Wait</h4>
  </div>
</div>

// react-coursera/src/components/AboutComponent.js
import React from 'react';
import { Breadcrumb, BreadcrumbItem, Card, CardBody, CardHeader, Media } from 'reactstrap';
import { Link } from 'react-router-dom';

function RenderLeader({ leader }) {
    return (
        <Media tag="li">
            <Media left middle>
                <Media object src={leader.image} alt={leader.name} />
            </Media>
            <Media body className="ml-5">
                <Media heading>{leader.name}</Media>
                <p>{leader.designation}</p>
                <p>{leader.description}</p>
            </Media>
        </Media>
    );
}

function About(props) {

    const leaders = props.leaders.map((leader) => {
        return (
            <div key={leader.id} className="col-12 mt-5">
                <RenderLeader leader={leader} />
            </div>
        );
    });

    return (
        <div className="container">
            <div className="row">
                <Breadcrumb>
                    <BreadcrumbItem><Link to="/home">Home</Link></BreadcrumbItem>
                    <BreadcrumbItem active>About Us</BreadcrumbItem>
                </Breadcrumb>
                <div className="col-12">
                    <h3>About Us</h3>
                    <hr />
                </div>
            </div>
            <div className="row row-content">
                <div className="col-12 col-md-6">
                    <h2>Our History</h2>
                    <p>Started in 2010, Ristorante con Fusion quickly established itself as a culinary icon par excellence in Hong Kong. With its unique brand of world fusion cuisine that can be found nowhere else, it enjoys patronage from the A-list clientele in Hong Kong.  Featuring four of the best three-star Michelin chefs in the world, you never know what will arrive on your plate the next time you visit us.</p>
                    <p>The restaurant traces its humble beginnings to <em>The Frying Pan</em>, a successful chain started by our CEO, Mr. Peter Pan, that featured for the first time the world's best cuisines in a pan.</p>
                </div>
                <div className="col-12 col-md-5">
                    <Card>
                        <CardHeader className="bg-primary text-white">Facts At a Glance</CardHeader>
                        <CardBody>
                            <dl className="row p-1">
                                <dt className="col-6">Started</dt>
                                <dd className="col-6">3 Feb. 2013</dd>
                                <dt className="col-6">Major Stake Holder</dt>
                                <dd className="col-6">HK Fine Foods Inc.</dd>
                                <dt className="col-6">Last Year's Turnover</dt>
                                <dd className="col-6">$1,250,375</dd>
                                <dt className="col-6">Employees</dt>
                                <dd className="col-6">40</dd>
                            </dl>
                        </CardBody>
                    </Card>
                </div>
                <div className="col-12">
                    <Card>
                        <CardBody className="bg-faded">
                            <blockquote className="blockquote">
                                <p className="mb-0">You better cut the pizza in four pieces because
                                    I'm not hungry enough to eat six.</p>
                                <footer className="blockquote-footer">Yogi Berra,
                                <cite title="Source Title">The Wit and Wisdom of Yogi Berra,
                                    P. Pepe, Diversion Books, 2014</cite>
                                </footer>
                            </blockquote>
                        </CardBody>
                    </Card>
                </div>
            </div>
            <div className="row row-content">
                <div className="col-12">
                    <h2>Corporate Leadership</h2>
                </div>
                <div className="col-12">
                    <Media list>
                        {leaders}
                    </Media>
                </div>
            </div>
        </div>
    );
}

export default About;
